#### Credentials
credentials:
  gcp_creds_file: "/src/gcp_creds.json"
  gbif_creds: ""
  ebird_api_key: "aopapml9tvuu"
  gbif_passw: ""
  gbif_user: ""
#### folders
folders:
  historical_data_folder: "../data/0163061-220831081235567.csv"
gcp_project:
  title: birdflow
  bucket_name: dtc_data_lake_us_birdflow
  gbq_dataset_raw: raw_bird_data
  gbq_dataset_processed: processed_bird_data