name:
  Update Bird Data
 
  # Controls when the workflow will run
on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "*/5 * * * *"
 
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install dependencies
        run: pip3 install -r src/requirements.txt
      - name: setup local project
        run: pip3 install -e .
      - name: update bird data 
        run: python3 src/launch_bird_flow_github_actions.py
  
      
